---
  database:
    type: "mysql"
    host: "localhost"
    port: 3306
    username: "typeorm_usr"
    password: "tYPe0rm!01"
    database: "typeorm_example"
    synchronize: true
  log4js:
    pm2: true
    appenders:
      stdout: # 標準出力
        type: 'console'
      stderr: # 標準エラー出力
        type: 'stderr'
      access: # アクセスログ
        type: "dateFile"
        filename: "/var/log/local/typeorm-example/access.log"
        pattern: "-yyyy-MM-dd"
        backups: 10
      error: # エラーログ
        type: "dateFile"
        filename: "/var/log/local/typeorm-example/error.log"
        pattern: "-yyyy-MM-dd"
        maxLogSize: 107374182400 # 100MB
      debug: # デバッグログ
        type: "file"
        filename: "/var/log/local/typeorm-example/debug.log"
        backups: 10
        maxLogSize: 10737418240 # 10MB
    categories:
      default:
        appenders:
          - 'stdout'
          - 'debug'
        level: 'debug'
      access:
        appenders:
          - 'stdout'
          - 'access'
        level: 'info'
      error:
        appenders:
          - 'stderr'
          - 'error'
        level: 'info'
  swagger:
    swagger: "2.0"
    info:
      title: "typeorm-example"
      version: 0.2.4
      description: "typeorm-example API。"
    basePath: "/api"
    consumes:
      - "application/json"
    produces:
      - "application/json"
    definitions:
      Error:
        type: object
        description: エラー情報
        properties:
          name:
            type: string
            description: エラー名称
          message:
            type: string
            description: エラーメッセージ
    parameters:
      offset:
        in: query
        name: offset
        description: 開始位置
        type: integer
        format: int32
      limit:
        in: query
        name: limit
        description: 取得件数
        type: integer
        format: int32
    responses:
      BadRequest:
        description: バリデーションNG
        schema:
          $ref: '#/definitions/Error'
      Unauthorized:
        description: 認証NG
        schema:
          $ref: '#/definitions/Error'
      Forbidden:
        description: 権限NG
        schema:
          $ref: '#/definitions/Error'
      NotFound:
        description: 該当データ無し
        schema:
          $ref: '#/definitions/Error'